<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211010556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, body_markdown TEXT NOT NULL, variables_json JSON DEFAULT NULL, visibility VARCHAR(50) NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97601F8332C8A3DE ON template (organization_id)');
        $this->addSql('CREATE INDEX IDX_97601F83B03A8386 ON template (created_by_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F8332C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE template DROP CONSTRAINT FK_97601F8332C8A3DE');
        $this->addSql('ALTER TABLE template DROP CONSTRAINT FK_97601F83B03A8386');
        $this->addSql('DROP TABLE template');
    }
}
